// Code generated by lesiw.io/plain. DO NOT EDIT.

package main

import (
	"embed"

	"lesiw.io/plain"
)

//go:embed sql/migrations/*
var _migrationFS embed.FS

func init() {
	plain.MigrationFS = _migrationFS
}
