// Code generated by lesiw.io/plain. DO NOT EDIT.

package stmt

const AddGroupEntry = `
insert into group_entry (url, "group", subject, body, date)
values ($1, $2, $3, $4, $5);
`

const GroupEntries = `
select url, "group", subject, body, date from group_entry order by date desc;
`

const GroupEntry = `
select 1 from group_entry where url = $1;
`
